CREATE TABLE clinical (
    sample_id                           VARCHAR2(50) NOT NULL PRIMARY KEY,
    sample_type_id                      NUMBER,
    sample_type                         VARCHAR2(100),
    primary_disease                     VARCHAR2(100),
    patient                             VARCHAR2(100),
    cancer_type_abbreviation            VARCHAR2(10),
    age_at_initial_pathologic_diagnosis NUMBER,
    gender                              VARCHAR2(10),
    race                                VARCHAR2(50),
    ajcc_pathologic_tumor_stage         VARCHAR2(50),
    clinical_stage                      VARCHAR2(50),
    histological_type                   VARCHAR2(100),
    histological_grade                  VARCHAR2(50),
    initial_pathologic_dx_year          NUMBER,
    menopause_status                    VARCHAR2(50),
    birth_days_to                       NUMBER,
    vital_status                        VARCHAR2(20),
    tumor_status                        VARCHAR2(50),
    last_contact_days_to                NUMBER,
    death_days_to                       NUMBER,
    cause_of_death                      VARCHAR2(100),
    new_tumor_event_type                VARCHAR2(100),
    new_tumor_event_site                VARCHAR2(100),
    new_tumor_event_site_other          VARCHAR2(100),
    new_tumor_event_dx_days_to          NUMBER,
    treatment_outcome_first_course      VARCHAR2(100),
    margin_status                       VARCHAR2(50),
    residual_tumor                      VARCHAR2(50)
);
